name: contract

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (root)
        run: npm ci
      - name: Emit OpenAPI (node)
        run: npm run openapi:emit:node
      - name: Lint OpenAPI
        run: npm run openapi:lint
      - name: Diff OpenAPI
        run: npm run openapi:diff
      - name: Generate Types
        run: npm run openapi:types
      - name: Generate Client
        run: npm run client:gen
      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: packages/generated/openapi.json
